### ISSUE TITLE
Replace target vector with categorical arrays?

### ISSUE THREAD

**Issue by peterTorrione** [covartech/PRT#22]
Seem to do a lot of what we already do, but faster and cleaner.

http://www.mathworks.com/help/matlab/matlab_prog/advantages-of-using-categorical-arrays.html

Advantages:

http://www.mathworks.com/help/matlab/matlab_prog/advantages-of-using-categorical-arrays.html

Disadvantage:
Lots of code to re-write; also breaks code for anyone not using 2013B.... which is bleeding-edge.  Will need to fork, and wait.  Back-burner for now, but potentially interesting.

**Comment by patrickkwang** [comment]
So, it's been 2.5 years. It may now be safe to require at least 2013b.

I like this idea but I'm a little concerned just because most other folks use numerical labels. All our external calls (like to libsvm) will have to convert to the standard format.

Running things like prtClassPlsda+prtDecisionBinaryMinPe currently outputs a prtDataSetClass, in which the 'data' are the predicted labels. In the proposed framework we might need something like a prtDataSetClassPrediction.

Things like prtScoreRoc will have to be told which label corresponds to a 'detection' vs a 'false alarm'.

**Comment by covartech** [comment]
I say we probably want to jettison this idea... things work the way they are, and changing it breaks a lot, and adds very little...

Unless I hear otherwise, close?
