### ISSUE TITLE
Warning: Could not find GraphViz installation

### ISSUE THREAD

**Issue by lyzhangjm** [covartech/PRT#30]
Hello, I have installed the  graphviz-2.38.msi , when I run prtSetup, the warning information is as follows:

Warning: Could not find GraphViz installation. Graphviz must be installed and on the system
path to enable prtAlgorithm plotting. Go to http://www.graphviz.org/ and follow the
installation instructions for your operating system. 
 Anyone konw ?  
Thank you!

**Comment by kennethmorton** [comment]
Hi,

This problem is typically caused by graphviz not being accessible from the MATLAB command line path. Fixing this is operating system dependent. Independent of this, due to changes in recent versions of graphviz, the PRT graphviz integration is currently in flux. We are working to resolve this. Until then, the only functionality missing will be prtAlgorithm plotting. So this warning should not be a major concern. If any issues come up please let use know and we will give you a work around if possible.

Kenny

**Comment by kennethmorton** [comment]
Update: The graphviz dependency has been completely removed. There is no longer a need to install.
