### ISSUE TITLE
Cross Validation

### ISSUE THREAD

**Issue by anaritam** [covartech/PRT#39]
I want to know the accuracy of a classifier by doing a cross validation using a "Leave-one-out" algorithm, so I used the command
classifier.kfolds(dataSet,length(labels))
How can I now the result from it? I tried using all the output variable as it's explained in
http://covartech.github.io/prtdoc/functionReference/prtClassKnn/kfolds.html
but I couldn't find the value indicating the accuracy of the classifier. Can anyone help?

Thanks,
Ana

**Comment by covartech** [comment]
Hi,

There is no single accuracy value embedded in the output; instead, you can score the output of KFOLDS with any of the prtScore* functions, e.g.:

ds = prtDataGenUnimodal;
classifier = prtClassFld;
yOut = classifier.kfolds(ds,ds.nObservations);
prtScoreRoc(yOut);  % Generate ROC scoring

or
ds = prtDataGenUnimodal;
ds = prtDataGenUnimodal;
classifier = prtClassFld + prtDecisionBinaryMinPe;
yOut = classifier.kfolds(ds,ds.nObservations);
prtScoreConfusionMatrix(yOut);  % Generate confusion matrix

Or: 
prtScorePercentCorrect(yOut)  % Get the percent correct
    0.9675

You can also simplify your k-folds call, since the default is leave-one-out:

yOut = classifier.kfolds(dataSet,length(labels));
yOut = classifier.kfolds(dataSet,dataSet.nObservations); % preferred
yOut = classifier.kfolds(dataSet);  %same thing

Hope this helps...

**Comment by anaritam** [comment]
Yes it helped very much! Thank you!
