### ISSUE TITLE
error during prtSetup

### ISSUE THREAD

**Issue by msmama** [covartech/PRT#40]
I have download the PRT from this web link   https://github.com/covartech/PRT
Unzip , keep in C:\Users\Administrator\Documents\MATLAB
>> prtDoc
>>prtSetup
Warning: Removed
'C:\Users\Administrator\Documents\MATLAB\covartech-PRT-e944d00\doc\functionReference\prtAction'
from the MATLAB path for this MATLAB session.
..
many more

**Comment by kennethmorton** [comment]
Hi,
Thanks for letting us known about this. 

This appears to be an issue with how MATLAB help is stored and interfaced with different versions of MATLAB.  prtSetup has a few jobs.

1) Checks your version of MATLAB to make sure it is newer than 2008a
2) Checks to see if you have graphviz installed. This is outdated as graphviz is no longer a requirement, and is unused by the PRT.
3) Organizes HTML documentation and interfaces it with the MATLAB documentation

Since the HTML setup appears to be at least partially broken, there is no reason other than reason (1) above to use prtSetup.

In the lastest version, prtSetup has been updated accordingly.

Thanks again,
Kenny



The HTML documentation system needs a little updating, so until we get this

**Comment by msmama** [comment]
Thank you sir 

1) version of Matlab 2014a
2) >> prtDoc gives error for graphvz
So Download graphviz-2.38.zip from this http://www.graphviz.org/Download_windows.php
    and unzip--- generate folder named as release, keep at C:\Program Files\release
Is it required to install -------graphviz-2.38.msi ????
Is it required to run prtSetup ????

3)  path varibale is set to -----
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\system32\Wbem;C:\Program Files\MiKTeX 2.9\miktex\bin;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\MATLAB\R2010a\runtime\win32;C:\Program Files\MATLAB\R2010a\bin;C:\Program Files\MATLAB\R2014a\runtime\win32;C:\Program Files\MATLAB\R2014a\bin;C:\Program Files\MATLAB\R2014a\polyspace\bin;C:\Program Files\release\bin;C:\Users\Administrator\Documents\MATLAB\PRT-master

4) Here I have past first and last few lines of the Error obtained at Matlab prompt

Warning: Removed
'C:\Users\Administrator\Documents\MATLAB\PRT-master\doc\functionReference\prtAction'
from the MATLAB path for this MATLAB session.
	See 'doc path' for more information. 
> In prtSetup at 69 
Warning: Removed
'C:\Users\Administrator\Documents\MATLAB\PRT-master\doc\functionReference\prtAlgorithm'
from the MATLAB path for this MATLAB session.
	See 'doc path' for more information. 
> In prtSetup at 69 >> prSetup

............... many more-----------

> In prtSetup at 69 
Warning: Removed 'C:\Users\Administrator\Documents\MATLAB\PRT-master\doc' from the
MATLAB path for this MATLAB session.
	See 'doc path' for more information. 
> In prtSetup at 69 
Warning: There is no installed product with this help location.
Documentation that is not associated with a product will not be displayed in the
help browser. 
> In builddocsearchdb at 33
  In prtSetup at 83 
Successfully created search database.
----------------------------

Please suggest what to do 
should I skip "prtSetup" and proceed to next step "Building MEX Files"

kindly reply

Regards

**Comment by msmama** [comment]
As per your instruction I have done the modification of the following three files
1. C:\Users\Administrator\Documents\MATLAB\PRT-master\doc\prtDoc.m
2. C:\Users\Administrator\Documents\MATLAB\PRT-master\engine\dataset\prtDataSetClass.m
3. C:\Users\Administrator\Documents\MATLAB\PRT-master\util\prtSetup.m

**Comment by msmama** [comment]
and successfully return the matlab prompt
