### ISSUE TITLE
Problem with targetNames with retainTargets()

### ISSUE THREAD

**Issue by patrickkwang** [covartech/PRT#59]
```
ds = prtDataSetClass('X',0,'Y',[0,0],'targetNames',{'first','second'});
ds1 = ds.retainTargets(1);
ds2 = ds.retainTargets(2);
ds1.targetNames
ds2.targetNames
```
`retainTargets()` seems to be doing the right thing, but `prtDataSetInMem.getTargetNames()` looks for a target name associated with index 1 and, not finding it, yields a default target name.

**Comment by peterTorrione** [comment]
Should be fixed in

https://github.com/covartech/PRT/commit/eb161c7c5bc64eb93fd4d3003cbb52d8faf19d58

<pre>
ds = prtDataSetClass('X',0,'Y',[0,0],'targetNames',{'first','second'});
ds1 = ds.retainTargets(1);
ds2 = ds.retainTargets(2);
ds1.targetNames
ds2.targetNames
</pre>

Should output:
<pre>
ans =
  cell
    'first'
ans =
  cell
    'second'
</pre>
